Added Crows and Bread Crumbs
fabric-community/spooky-time pull request #109
Opened 2019-10-06 15:47 UTC by Shnupbups

Added Crows. They currently don't spawn or have animations and only have a couple of sounds, but other than that they're pretty good.

Also added Bread Crumbs, craftable from Bread. You can eat them or place them down to make a trail, Hansel and Gretel style. But much like the fairy tale, Crows can eat them when placed down, destroying your trail.

2019-10-06 15:50 UTC, Shnupbups commented
The plan is to have a Gingerbread House structure spawn rarely in the Spooky Dimension, with Bread Crumbs leading to it. The structure will have a Witch Spawner as well as loot (and maybe some rotten flesh in a Smoker...).

2019-10-06 16:49 UTC, Draylar requested changes
Reviewing on a phone is hard.

:crab: style police have arrived :crab:

2019-10-06 16:49 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/BreadCrumbsBlock.java
> +	public static final VoxelShape SHAPE = Block.createCuboidShape(0.0D, 0.0D, 0.0D, 16.0D, 1.0D, 16.0D);
Should/could this be private?

2019-10-06 16:49 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/BreadCrumbsBlock.java
> +	public VoxelShape getOutlineShape(BlockState state, BlockView blockView, BlockPos pos, EntityContext context) {
@Override

2019-10-06 16:49 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/BreadCrumbsBlock.java
> +	public boolean canPlaceAtSide(BlockState state, BlockView blockView, BlockPos pos, BlockPlacementEnvironment bpe) {
@Override

2019-10-06 16:49 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/BreadCrumbsBlock.java
> +	public boolean canPlaceAt(BlockState state, ViewableWorld world, BlockPos pos) {
@Override

2019-10-06 16:49 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/BreadCrumbsBlock.java
> +	public BlockState getStateForNeighborUpdate(BlockState state, Direction direction, BlockState state2, IWorld world, BlockPos pos, BlockPos pos2) {
@Override

2019-10-06 16:49 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/CrowEntity.java
> +public class CrowEntity extends AnimalEntity implements Bird {
ctrl + f -> "_1" -> replace -> profit

2019-10-06 16:49 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/CrowEntity.java
> +	@Nullable
Remove Nullable annotation

2019-10-06 16:49 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/goal/EatBreadcrumbsGoal.java
> +public class EatBreadcrumbsGoal extends MoveToTargetPosGoal {
@Override and remove Nullable

2019-10-06 16:49 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/goal/TemptBirdGoal.java
> +public class TemptBirdGoal extends Goal {
@Override and remove Nullable

2019-10-06 17:56 UTC, Juuxel requested changes
:crab: more style comments :crab:

2019-10-06 17:56 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/client/model/CrowEntityModel.java
> +	private final Cuboid right_wing;
`camelCase` instead of `snake_case`

2019-10-06 17:56 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/client/render/CrowEntityRenderer.java
> +@SuppressWarnings({"rawtypes", "unchecked"})
What do you need these suppressions for? I don't see any generic types here.

2019-10-07 15:21 UTC, Juuxel approved these changes

2019-10-07 15:21 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/registry/SpookyBlocks.java
> +	public static final Block DEADER_BUSH = register("deader_bush", new DeaderBushBlock(FabricBlockSettings.copy(Blocks.DEAD_BUSH).materialColor(MaterialColor.BROWN).build()), new Item.Settings().group(
:+1:

2019-10-07 15:23 UTC, Shrimpstress approved these changes

2019-10-07 15:25 UTC, merged