General Dimension Improvements
fabric-community/spooky-time pull request #122
Opened 2019-10-09 03:08 UTC by Zundrel

Implement Tainted Stone and Cobblestone, enabled per biome fog color and intensity (smoothing is configurable), lowered purple-ness of dirt, set light levels to be normal, moved Pumpcown spawn to base biome.

2019-10-09 03:10 UTC, Zundrel commented
Also, as much as I'd love to fix all the _1 stuff in `SpookyOreFeature` I really have no clue what to do there, so I'm just going to leave it as is.

2019-10-09 03:11 UTC, Shnupbups approved these changes

2019-10-09 06:05 UTC, valoeghese requested changes

2019-10-09 06:05 UTC, valoeghese commented on src/main/java/com/fabriccommunity/spookytime/world/biome/SpookyBaseBiome.java
> +	public int getSkyColor(float skyColor) {
The parameter is temperature, not sky colour

2019-10-09 06:21 UTC, valoeghese requested changes

2019-10-09 06:21 UTC, valoeghese commented on src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyOreFeature.java
> +        float float_1 = random.nextFloat() * 3.1415927F;
randomNumberFromZeroToPi

2019-10-09 06:21 UTC, valoeghese commented on src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyOreFeature.java
> +        int int_6 = 0;
If I had to figure out what stuff did in the chunk generator pr to rename it you have to rename all these too

2019-10-09 06:21 UTC, valoeghese commented on src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyOreFeature.java
> +        Mutable blockPos$Mutable_1 = new Mutable();
At least name this variable “pos”

2019-10-09 06:21 UTC, valoeghese commented on src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyOreFeature.java
> +        for(int int_8 = int_3; int_8 <= int_3 + int_6; ++int_8) {
int_8 -> x
int_9 -> z
int_4 -> y

2019-10-09 06:22 UTC, valoeghese commented
Some of the local variables here are pretty easy to figure out

2019-10-09 06:23 UTC, valoeghese commented on src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyOreFeature.java
> +        for(int int_8 = int_3; int_8 <= int_3 + int_6; ++int_8) {
Similarly, int_3 would be `startX` and int_6 `xSize`

2019-10-09 06:24 UTC, valoeghese commented on src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyOreFeature.java
> +        int int_6 = 0;
You can just hardcode uses of int_6 to 0 if you don’t know what it does

2019-10-09 14:42 UTC, Shrimpstress commented
I’ll look into all of this further today, I did not bother with local variables last night because it was late.

2019-10-09 17:33 UTC, Zundrel commented
I've fixed all of your requested changes. There's quite a lot of names which I still don't have enough of an understanding to name them, so help on naming them would be appreciated.

2019-10-09 17:34 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/registry/SpookyFeatures.java
> +	private static <C extends SurfaceConfig, F extends SurfaceBuilder<C>> F register(String string_1, F surfaceBuilder_1) {
Is this method used?

2019-10-09 17:36 UTC, Zundrel commented on src/main/java/com/fabriccommunity/spookytime/registry/SpookyFeatures.java
> +	private static <C extends SurfaceConfig, F extends SurfaceBuilder<C>> F register(String string_1, F surfaceBuilder_1) {
No, but I included it since we may want to implement our own SurfaceBuilders in the future.

2019-10-09 17:36 UTC, Zundrel commented on src/main/java/com/fabriccommunity/spookytime/registry/SpookyFeatures.java
> +	private static <C extends SurfaceConfig, F extends SurfaceBuilder<C>> F register(String string_1, F surfaceBuilder_1) {
I'm fine with removing it until we actually need it, if you'd prefer.

2019-10-09 17:37 UTC, Juuxel requested changes

2019-10-09 17:37 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/registry/SpookyFeatures.java
> +	private static <C extends SurfaceConfig, F extends SurfaceBuilder<C>> F register(String string_1, F surfaceBuilder_1) {
It's fine, but you should give the parameters non-`_1` names and use `SpookyTime.id()`.

2019-10-09 17:40 UTC, Juuxel requested changes
:rotating_light: The style police has arrived yet again :rotating_light: 

Could you reindent the `tainted_stone` and `tainted_cobblestone` loot tables with tabs?

2019-10-09 17:46 UTC, Zundrel commented
Alright, loot tables are fixed to use tabs now and merge conflicts are fixed.

2019-10-09 18:46 UTC, Juuxel approved these changes

2019-10-09 22:23 UTC, vini2003 approved these changes
A few minor style inconsistencies here and there but seems solid.

2019-10-09 22:28 UTC, valoeghese requested changes

2019-10-09 22:28 UTC, valoeghese commented on src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyOreFeature.java
> +            double_13 = MathHelper.lerp((double)float_1, double_5, double_6);
I assume by analogy that double_5 and double_6 are probably positiveY and negativeY, respectively. That would make double_12 something like currentX, double_13 currentY, and double_14 currentZ

2019-10-09 22:30 UTC, valoeghese commented on src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyOreFeature.java
> +            double_13 = MathHelper.lerp((double)float_1, double_5, double_6);
Also float_1 is probably `progress`

2019-10-09 22:44 UTC, Zundrel commented
Alright I've updated this PR with your suggested names.

2019-10-10 04:44 UTC, Shnupbups commented
As soon as merge conflicts are resolved, this is ready for merge. I'd do it myself but I'm on my phone at the moment.

2019-10-10 06:04 UTC, merged