Placeable pumpkin pies & updated fr translation
fabric-community/spooky-time pull request #153
Opened 2019-10-16 13:03 UTC by Yanis48

Pumpkin pies can now be placed, with a block model and texture made by MoonlitLamps :)

Also I updated the French translation

2019-10-16 13:43 UTC, Shnupbups commented
Not a fan of overriding vanilla items. Any chance you could find a way to implement the functionality without overriding the vanilla Pumpkin Pie?

2019-10-16 13:47 UTC, Juuxel commented
You can use Fabric's `UseItemCallback`.

2019-10-17 18:54 UTC, Yanis48 commented
Any other opinions on this? Coz it's _much_ easier to keep my way. Using `UseBlockCallback` implies testing the placement in all cases, all sides, and both hands, which is too much for such a small feature

2019-10-17 19:01 UTC, Juuxel requested changes
I'd say replacing the item with a config toggle would be fine.

2019-10-17 19:01 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/registry/MinecraftItems.java
> +	public static final Item PUMPKIN_PIE = register(776, "pumpkin_pie", new BlockItem(SpookyBlocks.PUMPKIN_PIE, new Item.Settings().group(ItemGroup.FOOD).food(FoodComponents.PUMPKIN_PIE)));
You can use `Item.getRawId(Items.PUMPKIN_PIE)` here instead of hardcoding it.

2019-10-17 19:01 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/registry/MinecraftItems.java
> +	private static Item register(int index, String name, Item item) {
`int rawId`

2019-10-19 14:50 UTC, Yanis48 commented
Help, it's broken

2019-10-19 14:58 UTC, Yanis48 commented
Redoing it

2019-10-19 14:58 UTC, closed without merging