Add Skeleton Doots
fabric-community/spooky-time pull request #17
Opened 2019-10-02 07:01 UTC by arkav

doot doot.

2019-10-02 15:23 UTC, Zundrel commented
The rarity of skeletons spawning with trumpets should be increased in my opinion. A 1/4 chance is way too high. That being said, the rarity could possibly be increased in the spooky dimension. 

This also needs merge conflicts fixed.

2019-10-02 17:08 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/mixin/MixinAbstractSkeletonEntity.java
> +        if (random.nextInt(3) == 0) {
Should probably hike up the rarity to ~1/30 or so. Not sure if there's dimension context in the entity at this stage or not, but if there is, you could have a higher chance only in the spooky dimension (and lower everywhere else).

2019-10-02 22:44 UTC, Shrimpstress requested changes

2019-10-02 22:44 UTC, Zundrel commented on src/main/resources/assets/spookytime/sounds.json
> +    "subtitle": "subtitle.spookytime.doot"
You set the subtitle translation key here, but then never translated it in the `en_us.json`

2019-10-02 22:44 UTC, Zundrel commented on src/main/java/com/fabriccommunity/spookytime/common/SpookySounds.java
> +        return Registry.register(Registry.SOUND_EVENT, new Identifier(SpookyTime.MODID, name), new SoundEvent(new Identifier(SpookyTime.MODID, name)));
The Identifiers here should be swapped out do use `SpookyTime.id(name)` instead.

2019-10-03 09:24 UTC, Shnupbups requested changes
Decrease the spawn rate and this should be merge ready!

2019-10-04 00:32 UTC, liach commented on src/main/java/com/fabriccommunity/spookytime/mixin/AbstractSkeletonEntityMixin.java
> +        if (random.nextInt(3) == 0) {
The random should probably be obtained from the entity itself, and the limit of nextInt should be like 8

2019-10-05 15:51 UTC, Shnupbups commented
I've changed the chance to 1 in 50 by default (ignore the name of the commit saying 30) and made it configurable. Should be good to merge now.

2019-10-05 15:52 UTC, Shnupbups approved these changes

2019-10-05 15:56 UTC, Shrimpstress approved these changes

2019-10-05 15:59 UTC, Juuxel requested changes
Looks good. There are just some minor style issues. Could you reindent the added json files using 4 spaces or tab characters?

2019-10-05 15:59 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/registry/SpookyItems.java
> +  public static Item SPOOKY_TRUMPET = register("spooky_trumpet", new SpookyTrumpetItem(new Item.Settings().group(SpookyTime.GROUP)));
Inconsistent indentation here. The other lines use tabs.

2019-10-05 15:59 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/registry/SpookySounds.java
> +    {
Braces should be on the same line as the method declaration.

2019-10-05 15:59 UTC, Juuxel commented on src/main/resources/assets/spookytime/lang/en_us.json
> +  "subtitle.spookytime.doot": "Trumpet Doots Spookily"
Inconsistent indentation here as well. (Should be a tab)

2019-10-05 15:59 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/mixin/AbstractSkeletonEntityMixin.java
>  import net.minecraft.entity.mob.AbstractSkeletonEntity;
Not a major issue, but these imports aren't ordered in any way. Consider grouping them like they are in the original code.

2019-10-05 16:15 UTC, Juuxel approved these changes

2019-10-05 16:17 UTC, merged