attempt cursed lighting
fabric-community/spooky-time pull request #31
Opened 2019-10-02 22:57 UTC by cplir-c

2019-10-02 23:24 UTC, Zundrel commented
Any chance you could change this to only occur in the spooky dimension?

2019-10-02 23:37 UTC, Shrimpstress requested changes

2019-10-02 23:37 UTC, Zundrel commented on src/main/resources/spookytime.mixins.json
> +=======
Please grab the latest `spookytime.mixins.json` and replace this one, and add your own mixin to it. Something happened and causes this monstrosity.

2019-10-02 23:41 UTC, Zundrel commented
This also completely breaks fluid rendering.

2019-10-03 18:18 UTC, Zundrel commented
This has quite a lot of merge conflicts that need to be fixed.

2019-10-09 22:36 UTC, vini2003 requested changes
Quite a lot of merge conflicts need to be solved, as @Zundrel said.

2019-10-17 17:04 UTC, Zundrel commented
I'm closing this for now due to inactivity. Feel free to make a new PR when you get around to continuing this, if you decide to.

2019-10-17 17:04 UTC, closed without merging