Trick or Treating Revamp + extras
fabric-community/spooky-time pull request #55
Opened 2019-10-03 13:20 UTC by Shnupbups

- Trick or Treating now has a 1 in 100 (configurable) chance of resulting in a 'trick'
- Tricks will turn nearby villagers into witches instead of having them give you candy
- Tricks can be disabled altogether in the config
- A message now shows up on the action bar when you are trick or treating, which tells you the outcome (or why it's not working)
- Costumes are now defined in an item tag
- Baby Villagers no longer respond to trick or treating
- Baked Pumpkin Seeds can now be made in a Smoker
- Small other changes

2019-10-03 17:04 UTC, Shrimpstress requested changes
Overall looks great to me! Didn't notice any obvious formatting weirdness, and everything seems to be nice and concise. I'll approve this once my review items are either addressed in code or by you.

2019-10-03 17:04 UTC, Zundrel commented on src/main/java/com/fabriccommunity/spookytime/mixin/ServerPlayNetworkHandlerMixin.java
> +			if (SpookyTags.COSTUMES.contains(player.inventory.getArmorStack(i).getItem())) return true;
You should include brackets here as to make things slightly clearer.

2019-10-03 17:04 UTC, Zundrel commented on src/main/java/com/fabriccommunity/spookytime/mixin/ServerPlayNetworkHandlerMixin.java
> +			if (SpookyTags.COSTUMES.contains(inv.getInvStack(i).getItem())) return true;
You should include brackets here as to make things slightly clearer.

2019-10-03 18:17 UTC, Zundrel commented
This now have a merge conflict.

2019-10-04 00:35 UTC, liach approved these changes

2019-10-04 04:52 UTC, merged