Custom chunk generator
fabric-community/spooky-time pull request #79
Opened 2019-10-04 05:14 UTC by valoeghese

Currently just does the same thing as the overworld but can be edited later

2019-10-04 06:55 UTC, Shnupbups approved these changes

2019-10-04 18:11 UTC, Shrimpstress requested changes
Fix all usages of `_1, _2, etc` and fix merge conflicts and this gets my approval.

2019-10-05 06:32 UTC, valoeghese commented
That’s because it’s placeholder vanilla code

2019-10-05 06:32 UTC, valoeghese commented
Though most of it will probably stay

2019-10-05 09:07 UTC, Juuxel approved these changes

2019-10-05 09:07 UTC, merged