Ghastly desert + Spanish translations
fabric-community/spooky-time pull request #96
Opened 2019-10-05 00:11 UTC by emilyploszaj

Additions
* Ghastly Desert - a biomes that generates like a vanilla desert but spookier
* Spooky Cactus - like a vanilla cactus but spookier, and restless
* Deader Bush - dead bush but more dead
* Spanish translations - like English but with more tildes

2019-10-05 00:25 UTC, Shnupbups commented
Does Tainted Sandstone spawn in the Ghastly Desert?

2019-10-05 00:59 UTC, emilyploszaj commented
> 
> 
> Does Tainted Sandstone spawn in the Ghastly Desert?

no, that was added after I worked on generation

2019-10-05 08:48 UTC, Juuxel requested changes
I left some comments on `SpookyCactusBlock`. Also, could you remove `_1` and `_2` from the variables that have them?

2019-10-05 08:48 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +					int age = (Integer)state.get(AGE);
Unnecessary cast here.

2019-10-05 08:48 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +				}
A while loop would be clearer than an empty for loop here.

2019-10-05 08:48 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +	return OUTLINE_SHAPE;
Missing indentation here?

2019-10-05 08:48 UTC, Juuxel commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +			return (block_1 == SpookyBlocks.SPOOKY_CACTUS || block_1 == SpookyBlocks.TAINTED_SAND) && !world.getBlockState(pos.up()).getMaterial().isLiquid();
Missing indentation here as well.

2019-10-05 22:12 UTC, GiantNuker approved these changes
I don't know spanish, but it looks like you followed the style conventions :)

2019-10-05 22:41 UTC, Draylar approved these changes
I only have a bunch of style issues to address in my review. The content itself is great though, so I'm still approving.

:crab: style police is here :crab:

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/DeaderBushBlock.java
> +   public VoxelShape getOutlineShape(BlockState state, BlockView view, BlockPos pos, EntityContext context) {
Can we add `@Override` annotations just for clarity? I'll make a quick review comment on every instance of this I see, just so we can keep track of them.

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/DeaderBushBlock.java
> +   protected boolean canPlantOnTop(BlockState state, BlockView view, BlockPos pos) {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +	public void onScheduledTick(BlockState state, World world, BlockPos pos, Random random) {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +	public VoxelShape getCollisionShape(BlockState state, BlockView view, BlockPos pos, EntityContext context) {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +	public VoxelShape getOutlineShape(BlockState state, BlockView view, BlockPos pos, EntityContext context) {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +	public boolean isOpaque(BlockState state) {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +	public BlockState getStateForNeighborUpdate(BlockState state, Direction direction, BlockState state2, IWorld world, BlockPos pos, BlockPos pos2) {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +	public boolean canPlaceAt(BlockState state, ViewableWorld world, BlockPos pos) {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +	public void onEntityCollision(BlockState state, World world, BlockPos pos, Entity entity) {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +	public BlockRenderLayer getRenderLayer() {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +	protected void appendProperties(StateFactory.Builder<Block, BlockState> builder) {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +	public boolean canPlaceAtSide(BlockState state, BlockView view, BlockPos pos, BlockPlacementEnvironment environment) {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/SpookyCactusEntity.java
> +	protected void initGoals() {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/SpookyCactusEntity.java
> +	protected void initAttributes() {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/SpookyCactusEntity.java
> +	protected void initDataTracker() {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/world/feature/DeaderBushFeature.java
> +	public boolean generate(IWorld world, ChunkGenerator<? extends ChunkGeneratorConfig> generator, Random random, BlockPos pos, DefaultFeatureConfig config) {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyCactusFeature.java
> +	public boolean generate(IWorld world, ChunkGenerator<? extends ChunkGeneratorConfig> generator, Random random, BlockPos pos, DefaultFeatureConfig config) {
`@Override`

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +	}
Might make sense to just same-line these without the static block.

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
> +				SpookyCactusEntity entity = new SpookyCactusEntity(SpookyEntities.SPOOKY_CACTUS, world);
I think we should have a newline before the entity just to split off the if-statement.

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/client/render/SpookyCactusEntityRenderer.java
> +		for(int i = 0; i < entity.getCactusHeight(); i++){
Could we newline out the if-statement on the front and back, just for clarity?

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/SpookyCactusEntity.java
> +		CACTUS_HEIGHT = DataTracker.registerData(SpookyCactusEntity.class, TrackedDataHandlerRegistry.INTEGER);
I would just same-line this unless there's a particular reason for the static block.

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/SpookyCactusEntity.java
> +			if (hop > 0) {
newline before hop statement

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/SpookyCactusEntity.java
> +				setPositionAndAngles(x - moveX, y, z - moveZ, yaw - moveAngle, this.pitch);
same here, newline before hop check

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/SpookyCactusEntity.java
> +				}
let's separate this statement out with newlines on front and end

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/SpookyCactusEntity.java
> +	}
Forgot a newline after the method body.

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/SpookyCactusEntity.java
> +	}
Here as well; just newline after the method body.

2019-10-05 22:41 UTC, Draylar commented on src/main/java/com/fabriccommunity/spookytime/entity/SpookyCactusEntity.java
> +
Extra newline hiding in the back~

2019-10-06 03:04 UTC, Shnupbups approved these changes

2019-10-06 03:04 UTC, merged